### ISSUE TITLE
v1.0.35 - experiencing random Software panic reset

### ISSUE THREAD

**Issue by chrisyoung72cy-lang** [shufps/ESP-Miner-NerdQAxePlus#436]
Since upgrading to v1.0.35 recently my NerdQaxe++ has randomly been resetting itself - reporting "Software Panic Reset".
Sometimes its 2hrs, other times its 12 hours before it resets.....

anybody else seeing this issue?

i am overclocking, but my temperatures are stable at 55 degC and i have been running this configuration fore several months with no issues until now.

![Image](https://github.com/user-attachments/assets/f2f534a9-7918-497a-890a-63d1764e0be0)

**Comment by kukulle-hood** [comment]
@chrisyoung72cy-lang 
Hi, never had this, ...did not even know about this.
I am also overclocking on 750MHz and 1.190V on the Chip.

Are there somwhere "rules" when a "panic reset" is allowed to happen?
Maybe undervoltage from PSU, or even short power-interruption in the PSU....but then it probably says reset because of powerloss, ...I dont know.
Robert

**Comment by chrisyoung72cy-lang** [comment]
UPDATE: i was running in Dual Pool mode when its was software panic resetting - 50% BC2/50% BCH - yesterday i switched back to single pool mode ant its been fine, no issues for last 20hrs.
Might be an issue with Dual Pool mode?

will keep monitoring..

**Comment by shufps** [comment]
> Might be an issue with Dual Pool mode?

Hmm, can you please write which pools you were using? Then I can test it with the exact same pools. 🙏

**Comment by chrisyoung72cy-lang** [comment]
https://bc2.solopool.org/
https://bch.solopool.org/

**Comment by alucine** [comment]
The same here, with only one pool

<img width="1344" height="2992" alt="Image" src="https://github.com/user-attachments/assets/7f07b633-33b5-44e0-8121-6e0ea6dd1549" />

**Comment by shufps** [comment]
> The same here, with only one pool

What pool did you use?

**Comment by shufps** [comment]
> https://bc2.solopool.org/ https://bch.solopool.org/

thx, I'll try it 👍 

Just checked, my Haxe is running on dual pool (ckpool and eusolo ckpool) since 1.0.35 release and didn't have a software panic reset 🤔 

<img width="402" height="126" alt="Image" src="https://github.com/user-attachments/assets/c02f9486-c4a1-4db5-ba24-142787ae468e" />

Maybe the pools you are using is doing something that makes the fw crash 🤔 

I'll test your pools 👍

**Comment by alucine** [comment]
> > The same here, with only one pool
> 
> What pool did you use?

eu2.solopool.org

After one Hard reboot, power off and power on is working. With panic Reset not works

My setting is 750/1240, the stock setting in v3.1 nerdoctaxe

**Comment by shufps** [comment]
> eu2.solopool.org

ah you both are using solopool - that's a good sign that it might be the pool 👍

**Comment by shufps** [comment]
and which port are you connecting to? There seem to be different.

**Comment by alucine** [comment]
> and which port are you connecting to? There seem to be different.

Port 8002

I will change to letsmine pool 

de1.letsmine.it
3334
d=250000

**Comment by shufps** [comment]
why are you mining with fixed 250k? That doesn't make any sense ... 😑 

It can be that you don't submit a single share in an hour and the watchdog resets the device.

But it should say "watchdog reset" and not "software panic reset".

I'll let it run ... let's see ...

**Comment by alucine** [comment]
> why are you mining with fixed 250k? That doesn't make any sense ... 😑

Because this pool has a minimum difficulty of 250,000, I've seen that the Nerdoctaxe sends about 220 hashes in 6 hours, while my other Bitaxe Gamma sends about 26 hashes in 6 hours and has no problems with version 2.11.

I've changed the pool to Letsmine with the same minimum difficulty to see if, after several hours, the dashboard continues to respond as it did after a reboot.

**Comment by alucine** [comment]
> > and which port are you connecting to? There seem to be different.
> 
> Port 8002
> 
> I will change to letsmine pool
> 
> de1.letsmine.it 3334 d=250000

With another pool today no more panic Reset

**Comment by shufps** [comment]
I tried your pool and it's been running for 1.5 days now 🤔 

No panic (unfortunately). Such things are hard to catch ...

**Comment by shufps** [comment]
No idea, I was not able to reproduce this issue.

One thing though, on such high difficulties it might happen that the device doesn't submit a single share within a single hour what leads to the watchdog rebooting.

The "reboot reason" should be different though.

**Comment by a302nsyd** [comment]
Hello @shufps ,

First of all, thank you so much for what you do for all of us NerdQAxe++ users!

I too experienced software panic resets on my NerdQaxe++ Rev6 & NerdQaxe++ Hydro, within 30 minutes of installation of v1.0.35 for one miner and 6.5 hours for the other. 

I am and have been solo mining BCH on viaBTC.com (bitcoin.viabtc.com; 3333 <-- their Smart Mining URL), with 650/1160 on the Rev6 & 660/1170 on the Hydro. Both are SINGLE pool mining. 

Like the OP, my miners having been running the same setup and pool for months, error-free, until v1.0.35.

Under v1.0.35, I also started seeing an error message pop up on the HTTP GUI every so many minutes about some value being missing or set to 0 (unknown error) or something similar; I just can't exactly recall...sorry.

Shares were being submitted/accepted at the normal pace/rate on v1.0.35.

I reinstalled v1.0.34.1 on both miners after they both experienced a software panic reboot. No more issues or errors with v1.0.34.1 reloaded.

I hope this helps - Thanks!

**Comment by chrisyoung72cy-lang** [comment]
i went back to v1.0.34.1 and its working fine - no more software panic resets so far

**Comment by nekrozon** [comment]
+1 ... rev5 seems fine ... but seeing this on a brand new rev 6.1

local pool

**Comment by shufps** [comment]
Crashes were cause by #453 . The API fetcher needed too much RAM on the stack and it crashed randomly. This was fixed somewhen between `-test1` and `-test6`

**Comment by a302nsyd** [comment]
Software Panic Resets are still happening with v1.0.36 on my NerdQaxe++ Rev6 and my NerdQaxe++ Hydro (every other day or so).

I am solo mining BTC on viaBTC.com (bitcoin.viabtc.com; 3333 <-- their Smart Mining URL), with 650/1160 on the Rev6 and 660/1170 on the Hydro. Both miners are SINGLE pool mining.

Like the OP, my miners having been running the same setup and pool for months on end, error-free, until v1.0.35.

Shares were being submitted/accepted at the normal pace/rate on v1.0.35 and v1.0.36.

I reinstalled v1.0.34.1 on both miners after they both experienced multiple software panic resets. No more issues or errors with v1.0.34.1 reloaded.

If there's something I can pull out of the logs to help with this issue, please let me know how/what in detail and I'll do my best to provide you with what you require.

Thank you
